### ISSUE TITLE
flexmark HTML Render not work in Intellij2020.1

### ISSUE THREAD

**Issue by ginfung** [ballerina-platform/lsp4intellij#262]
**Description:**

I notice that the `flexmark.html.HtmlRenderer` is not working in Intellij2020.1.
Checking in [this](https://github.com/ballerina-platform/lsp4intellij/blob/master/src/main/java/org/wso2/lsp4intellij/requests/HoverHandler.java) page, I found that as long as we create the `HtmlRenderer` object, the IDE would not show anything when we hovered.

If I removed all `flexmark` related code, and manually overwrite the html, the IDE on-hover feature works well.

Any hints or suggestions?

**Comment by ginfung** [comment]
It turns out that this was due to my wrong setups. The error type was `NoClassDefFoundError `.
